### ISSUE TITLE
misleading example

### ISSUE THREAD

**Issue by roccomuso** [vacuumlabs/cardano-crypto.js#10]
```js
var lib = require('cardano-crypto.js')

var mnemonic = 'logic easily waste eager injury oval sentence wine bomb embrace gossip supreme'
var walletSecret = await lib.walletSecretFromMnemonic(mnemonic, 1)
...
```
will throw

> TypeError: lib.walletSecretFromMnemonic is not a function

where is defined that method?

**Comment by refi93** [comment]
Sorry, it's the old API of the library, the equivalent function in the new one is called "mnemonicToRootKeypair" You can take a look at index.js and the tests in test/index.js folder to get a better idea about the API of the library. I will update that example in the readme.

**Comment by refi93** [comment]
fixed in https://github.com/vacuumlabs/cardano-crypto.js/commit/e4c6090ca3664eb2eaca29bbbe1ccdc7e81c060a
