### ISSUE TITLE
get transaction builder

### ISSUE THREAD

**Issue by roccomuso** [vacuumlabs/cardano-crypto.js#12]
It would be really useful to have also the transaction builder code extracted from adalite.
In this way we can easily reuse code.

Thanks!

**Comment by jamesscaur** [comment]
Agreed - I would like this too :)

**Comment by refi93** [comment]
sorry for the very late reply - for transaction building I'd recommend using rather https://github.com/Emurgo/cardano-serialization-lib which is a lot more advanced lib for Cardano, this lib is supposed to contain just the bare-bone minum. The only downside I know of is that it's wasm-based (the version transpiled to js being very slow), but at this point it should be feasible to run wasm code AFAIK on pretty much all relevant platforms, though I agree it may not be as convenient to set up :)
