### ISSUE TITLE
remove the "browserification" for Node JS and React Native

### ISSUE THREAD

**Issue by mubashir-tnm** [vacuumlabs/cardano-crypto.js#39]
I am working on kadena project and i need to create wallet for kadena in mobile app using `cardano-crypto.js`.
now problem is that `jam@chainweaver-keygen` fork of `https://github.com/kadena-io/cardano-crypto.js` which is browserified (uses browserify code) and it only works in browser base applications like React JS applications.
fork have not sport for node js or mobile app (react native etc).

**in node JS applications, error appears like this**
`Error: Secure random number generation is not supported by this browser.
Use Chrome, Firefox or Internet Explorer 11`

**in React Native, error appears**
`ReferenceError: Can't find variable: document`

actually problem is with browserify packages that only runs for browsers

**Comment by refi93** [comment]
sorry for the late reply, there is no browserification involved in the version of this lib in this repo, I guess you are referring to this specific branch which indeed involves browserification: https://github.com/kadena-io/cardano-crypto.js/commits/jam%40chainweaver-keygen so this code will likely need to be modified to fit your needs but this needs to be done by the author, so I suggest either contacting the author or making a fork yourself and just dropping the browserification which probably isn't essential for the forked lib to work
