### ISSUE TITLE
Using pure JS libs

### ISSUE THREAD

**Issue by roccomuso** [vacuumlabs/cardano-crypto.js#8]
Why building required libs from C files when there are JS modules for ed25519 or blake2b available?

**Comment by refi93** [comment]
Yes, there are, but Cardano has slight modifications to ed2559 (https://cardanolaunch.com/assets/Ed25519_BIP.pdf) and it implements a custom derivation scheme over it which in fact we originally ported to js. But it was just too much work to port all the little details and maintain them (e.g. when they added a new derivation scheme), so we decided just to take their reference c implementation and transpile it to js, making only the necessary bindings which isn't that much work and it does its job as well if not better than the manually ported version. The manually ported version was not a library, we ported it directly to the source code of adalite https://github.com/vacuumlabs/adalite/tree/develop - it should be in some older commits (we switched to cardano-crypto.js roughly around july 2018 - https://github.com/vacuumlabs/adalite/commit/da6a30d7c0fe416466eed833b07bad7ff97f4682)
